### PR TITLE
Added Stargazer Wallet Support

### PR DESCRIPTION
**Pull request by juandavidkincaid**
### Changes
+ Adds support for the stargazer injected wallet provider.

### Notes
https://constellationnetwork.io/discover/wallets-utilities/#stargazer-wallet

### DRIs
[juan@constellationnetwork.io](https://github.com/juandavidkincaid) - cc [alex@constellationnetwork.io](https://github.com/alexbrandes)

### CODE REVIEW

**Comment by samuveth** [comment]
Hi @juandavidkincaid, does this wallet support EIP712 typed data signing?

**Comment by juandavidkincaid** [comment]
Hello @samuveth, we currently only support the `personal_sign` [(EIP-192)](https://eips.ethereum.org/EIPS/eip-191) method, we tested creating proposals and it seemed to work fine. Would we need to add [EIP-712](https://eips.ethereum.org/EIPS/eip-712) support for the integration to work properly? We noticed there is wallet-specific code for _walletlink_ and _walletconnect_...

**Comment by samuveth** [comment]
@juandavidkincaid Yes we are in the late stages or moving to EIP712 and can unfortunately only integrate new wallets that support it.

**Comment by juandavidkincaid** [comment]
@samuveth ummm oko... We'll implement [EIP-712](https://eips.ethereum.org/EIPS/eip-712) in the next few days then... The current code here will not change... Should I close this PR or leave it open for the next days, just 3 - 5?

**Comment by samuveth** [comment]
@juandavidkincaid great, yes you can leave it open.

**Comment by juandavidkincaid** [comment]
Hi @samuveth, yesterday we deployed Stargazer 3.6.1 with support for [EIP-712](https://eips.ethereum.org/EIPS/eip-712), so we are ready for the next steps.

**Pull request merged**
